version: "3"

services:
  mongo:
    image: mongo:5.0
    env_file:
      - .env
    command: mongod --port 27017 --storageEngine wiredTiger
    volumes:
      - ./mongo_data:/data/db
    ports:
      - "27017:27017"

